version: "3.9"

networks:
  internal:         # traffic only inside the cluster
    internal: true
  public:           # exposed to host (gateway + client only)
  dbnet:            # databases + the services that need them

services:
  # ──────────────────────────────────────────── GATEWAY
  gateway:
    build: ./gateway
    container_name: gateway
    ports: [ "8080:8080" ]            # ← ONLY host-visible backend
    environment:
      USER_SVC_URL:       http://user-service:3001/
      SHORTENER_SVC_URL:  http://shortener-service:3002/
      QR_SVC_URL:         http://qr-service:8000/
    networks:
      - public
      - internal

  # ──────────────────────────────────────────── FRONT-END
  client:
    build: ./client
    container_name: client
    ports: [ "5173:5173" ]            # ← ONLY host-visible frontend
    environment:
      VITE_GATEWAY_URL:  http://localhost:8080
    networks:
      - public

  # ──────────────────────────────────────────── USER SERVICE
  user-service:
    build:
      context: ./user-service
      args: { PORT: 3001 }
    environment:
      SVC_NAME: user-service
    container_name: user-service
    ports:
      - "3001:3001"
    networks:
      - internal
      - dbnet

  # ──────────────────────────────────────────── SHORTENER SERVICE
  shortener-service:
    build:
      context: ./shortener-service
      args: { PORT: 3002 }
    environment:
      SVC_NAME: shortener-service
      REDIS_URL: redis://redis:6379
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    container_name: shortener-service
    ports: [ "3002:3002" ]            # ← Added host access
    networks:
      - public                         # ← Added public network
      - internal
      - dbnet

  # ──────────────────────────────────────────── QR SERVICE
  qr-service:
    build: ./qr-service
    container_name: qr-service
    ports: [ "8000:8000" ]            # ← Added host access
    networks:
      - public         
      - internal

  # ──────────────────────────────────────────── DATABASES
  postgres:
    image: postgres:16
    container_name: users-db
    ports: [ "5432:5432" ]
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: users
    volumes: [ "pgdata:/var/lib/postgresql/data" ]
    networks:
      - dbnet

  redis:
    image: redis:7
    container_name: shortener-redis
    ports: [ "6379:6379" ]
    networks:
      - dbnet

volumes:
  pgdata:
